### **IMPORTO LIBRERIE**

In [38]:
import pandas as pd

### **IMPORTO DATI**

In [39]:
#Importo i dataframe precedentemente puliti per l'analisi
df_software_outlier_medi = pd.read_csv("datas/processed/dataset_software_outlier_medi.csv")
df_hardware_outlier_medi = pd.read_csv("datas/processed/dataset_hardware_outlier_medi.csv")
df_software_outlier_singoli = pd.read_csv("datas/processed/dataset_software_outlier_singoli.csv")
df_hardware_outlier_singoli = pd.read_csv("datas/processed/dataset_hardware_outlier_singoli.csv")

### **STATISTICA DESCRITTIVA**

In [40]:
colonne_descrittive = [
    "roe_medio",
    "debt_equity_medio",
    "liquidita_media",
    "log_attivo_medio",
]

# Preparo la tabella con le statistiche descrittive per le colonne selezionate
statistica_descrittiva_outlier_singoli = df_software_outlier_singoli[colonne_descrittive].agg([
    "mean",
    "median",
    "std",
    "min",
    "max"
])

statistica_descrittiva_outlier_medi = df_software_outlier_medi[colonne_descrittive].agg([
    "mean",
    "median",
    "std",
    "min",
    "max"
])

In [41]:
statistica_descrittiva_outlier_medi

         roe_medio  debt_equity_medio  liquidita_media  log_attivo_medio
mean    -21.953420           1.114155         2.451601         13.137716
median   -9.725100           0.874898         1.941200         13.525409
std      41.643130           0.994601         1.536617          2.317436
min    -162.041333          -1.891752         0.068000          6.358121
max      83.872250           4.182277         7.545600         19.751048

In [42]:

statistica_descrittiva_outlier_singoli

        roe_medio  debt_equity_medio  liquidita_media  log_attivo_medio
mean    -7.263885           1.018388         2.258847         13.726328
median  -3.916600           0.835998         1.942000         13.891965
std     23.129421           0.691160         1.153141          2.149706
min    -85.430800          -0.127971         0.068000          6.803587
max     55.448000           3.394589         5.506500         19.751048