### **IMPORTO LIBRERIE**

In [20]:
import pandas as pd

### **IMPORTO DATI**

In [21]:
#Importo i dataframe precedentemente puliti per l'analisi
df_software = pd.read_csv("datas/processed/dataset_software_pulito.csv")
df_hardware = pd.read_csv("datas/processed/dataset_hardware_pulito.csv")

df_software.head()

,Unnamed: 0,Ragione socialeCaratteri latini,Inactive,Quoted,Branch,OwnData,Woco,Codice ISO paese,"Codice NACE Rev. 2, core code (4 cifre)",Codice di consolidamento,...,Totale Attivo\nmigl USD 2021,Totale Attivo\nmigl USD 2020,Totale Attivo\nmigl USD 2019,Totale Attivo\nmigl USD 2018,Totale Attivo\nmigl USD 2017,Totale Attivo\nmigl USD 2016,log_attivo_medio,roe_medio,debt_equity_medio,liquidita_media
0,1.0,ALPHABET INC.,No,Sì,No,No,Sì,US,6209,C1,...,359268000.0,319616000.0,275909000.0,232792000.0,197295000.0,167497000.0,19.747321,25.7126,0.418992,2.4474
1,2.0,MICROSOFT CORPORATION,No,Sì,No,No,Sì,US,5829,C1,...,333779000.0,301311000.0,286556000.0,258848000.0,250312000.0,193468000.0,19.751048,38.4348,1.198747,1.8590
2,3.0,"META PLATFORMS, INC.",No,Sì,No,No,Sì,US,6209,C1,...,165987000.0,159316000.0,133376000.0,97334000.0,84524000.0,64961000.0,19.108333,26.4742,0.411812,3.2114
3,7.0,"UBER TECHNOLOGIES, INC.",No,Sì,No,No,Sì,US,6209,C1,...,38774000.0,33252000.0,31761000.0,23988000.0,15426000.0,15713000.0,17.460193,-24.1302,2.116903,1.1446
4,8.0,SALESFORCE INC,No,Sì,No,No,Sì,US,5829,C1,...,95209000.0,66301000.0,55126000.0,30737000.0,21984000.0,17584923.0,18.331771,5.9436,0.657138,1.0914

### **STATISTICA DESCRITTIVA**

In [ ]:
colonne_descrittive = [
    "roe_medio",
    "debt_equity_medio",
    "liquidita_media",
    "log_attivo_medio",
]

# Preparo la tabella con le statistiche descrittive per le colonne selezionate
statistica_descrittiva = df_software[colonne_descrittive].agg([
    "mean",
    "median",
    "std",
    "min",
    "max"
])

statistica_descrittiva

                        mean     median        std         min        max
roe_medio         -21.953420  -9.725100  41.643130 -162.041333  83.872250
debt_equity_medio   1.114155   0.874898   0.994601   -1.891752   4.182277
liquidita_media     2.451601   1.941200   1.536617    0.068000   7.545600
log_attivo_medio   13.137716  13.525409   2.317436    6.358121  19.751048